import type { Agent } from '../../types'

const now = new Date().toISOString()

export const presetAgents: Agent[] = [
  {
    id: 'router',
    name: '路由调度',
    icon: '🧭',
    description: '分析用户意图并路由到合适 Agent',
    type: 'preset',
    role: 'router',
    enabled: true,
    systemPrompt: '你是一个路由器。',
    promptVersion: 1,
    promptHistory: [],
    skillIds: [],
    mcpServerIds: [],
    canDelete: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'homework-tutor',
    name: '作业辅导',
    icon: '📝',
    description: '解析作业题目并提供引导',
    type: 'preset',
    role: 'executor',
    enabled: true,
    systemPrompt: '你是一位经验丰富的小学教师。',
    promptVersion: 1,
    promptHistory: [],
    skillIds: ['ocr_parse', 'rag_search', 'calculator'],
    mcpServerIds: [],
    canDelete: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'study-planner',
    name: '学习规划',
    icon: '📅',
    description: '制定学习计划',
    type: 'preset',
    role: 'executor',
    enabled: true,
    systemPrompt: '你是一位学习规划教练。',
    promptVersion: 1,
    promptHistory: [],
    skillIds: ['task_create', 'rag_search'],
    mcpServerIds: [],
    canDelete: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'knowledge-qa',
    name: '知识问答',
    icon: '💡',
    description: '基于知识库回答问题',
    type: 'preset',
    role: 'executor',
    enabled: true,
    systemPrompt: '你是一位学科答疑助手。',
    promptVersion: 1,
    promptHistory: [],
    skillIds: ['rag_search', 'web_search'],
    mcpServerIds: [],
    canDelete: false,
    createdAt: now,
    updatedAt: now,
  },
]
